---
- name: Add a Linux Red Hat device to ServiceNow CMDB
  hosts: localhost # Run this task on the Ansible control node
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  # Define variables (use Ansible Vault for sensitive data!)
         # The IP address of the device
  vars:
      new_ci_ip: '192.192.192.192'
      new_ci_name: 'jp-demo-server1'
  tasks:
    - name: Create or Update Configuration Item in cmdb_ci_server
      servicenow.itsm.configuration_item:
        
        # --- CI Identification ---
        state: present                          # Ensures the CI exists
        sys_class_name: 'cmdb_ci_server'        # Specifies the CMDB table (Server class)
        
        # --- Core Attributes ---
        name: "{{ new_ci_name }}"               # The name of the CI (usually FQDN)
        ip_address: "{{ new_ci_ip }}"           # Primary IP address
        
        # --- Linux/Red Hat Specific Attributes ---
        os: 'Linux'                             # Operating System
        os_version: 'Red Hat Enterprise Linux 9' # Specific OS version
        
        # --- Other Example Attributes (Optional) ---
        install_status: 1                       # 1 = Installed
        manufacturer: 'Red Hat'                 # Manufacturer
        model_id: 'Virtual Machine'             # Model type
        # other:                                # Use 'other' for fields not exposed as top-level parameters
        #   assignment_group: 'Linux Team'
      
      register: new_ci
      
    - name: Display new CI details
      ansible.builtin.debug:
        msg: "Successfully created/updated CI: {{ new_ci.record.name }} with sys_id: {{ new_ci.record.sys_id }}"