---
- name: Add a Linux Red Hat device to ServiceNow CMDB
  hosts: localhost # Run this task on the Ansible control node
  connection: local
  gather_facts: false
  collections:
    - servicenow.itsm

  # Define variables (use Ansible Vault for sensitive data!)
         # The IP address of the device
  vars:
      new_ci_ip: '192.192.192.192'
      new_ci_name: 'jp-demo-server1'
  tasks:
    - name: Create or Update Configuration Item in cmdb_ci_server
      servicenow.itsm.configuration_item:
        state: present
        sys_class_name: 'cmdb_ci_server'
        name: "{{ new_ci_name }}"
        ip_address: "{{ new_ci_ip }}"
        install_status: 1                                 # 1 = Installed

        # --- Unsupported fields moved to the 'other' parameter ---
        # The keys here must match the backend field names in the 'cmdb_ci_server' table.
        other:
          # Device/OS Details (Common field names in cmdb_ci_server)
          manufacturer: 'Red Hat'
          model_id: 'Virtual Machine'                     # Use 'Virtual Machine' or a specific model sys_id
          os: 'Linux Red Hat'
          os_version: 'Red Hat Enterprise Linux 9'
      
      register: new_ci
      
    - name: Display new CI details
      ansible.builtin.debug:
        msg: "Successfully created/updated CI: {{ new_ci.record.name }} with sys_id: {{ new_ci.record.sys_id }}"